CREATE TABLE harvests
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    mushroom_id BIGINT                                  NOT NULL,
    grow_id     BIGINT,
    weight      DOUBLE PRECISION                        NOT NULL,
    date_harvested DATE                                NOT NULL,
    CONSTRAINT pk_harvests PRIMARY KEY (id)
);

ALTER TABLE harvests
    ADD CONSTRAINT FK_HARVESTS_ON_GROW FOREIGN KEY (grow_id) REFERENCES grows (id);

ALTER TABLE harvests
    ADD CONSTRAINT FK_HARVESTS_ON_MUSHROOM FOREIGN KEY (mushroom_id) REFERENCES mushrooms (id);