CREATE TABLE boxes
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT box_pk PRIMARY KEY (id)
);

CREATE TABLE grows
(
    date_started      date                                    NOT NULL,
    development_stage VARCHAR(255)                            NOT NULL,
    is_active         BOOLEAN,
    box_id            BIGINT                                  NOT NULL,
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT grows_pk PRIMARY KEY (id)
);

CREATE TABLE ideal_conditions
(
    development_stage VARCHAR(255) NOT NULL,
    temperature_high  FLOAT8       NOT NULL,
    temperature_low   FLOAT8       NOT NULL,
    humidity_high     FLOAT8       NOT NULL,
    humidity_low      FLOAT8       NOT NULL,
    mushroom_id       BIGINT       NOT NULL
);

CREATE TABLE measured_conditions
(
    date_time   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    temperature FLOAT8,
    humidity    FLOAT8,
    box_id      BIGINT                      NOT NULL,
    CONSTRAINT measured_conditions_pk PRIMARY KEY (date_time, box_id)
);

CREATE TABLE mushrooms
(
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    grow_id     BIGINT,
    CONSTRAINT mushrooms_pk PRIMARY KEY (id)
);

ALTER TABLE ideal_conditions
    ADD CONSTRAINT ideal_conditions_pk PRIMARY KEY (mushroom_id, development_stage);

ALTER TABLE measured_conditions
    ADD CONSTRAINT box_id FOREIGN KEY (box_id) REFERENCES boxes (id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE mushrooms
    ADD CONSTRAINT grow_id FOREIGN KEY (grow_id) REFERENCES grows (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE ideal_conditions
    ADD CONSTRAINT mushroom_id FOREIGN KEY (mushroom_id) REFERENCES mushrooms (id) ON UPDATE NO ACTION ON DELETE NO ACTION;