name: CI/CD Pipeline Master Deployment

on:
  workflow_dispatch:
  push:
    branches: [ rework-to-use-compute-engine-and-docker ]

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run Tests
        run: mvn -B test

  build:
    needs: tests
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Docker image
        run: docker build -t martybobo/fungeye .
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Configure Docker to use GCR
        run: gcloud auth configure-docker eu.gcr.io
      - name: Push Docker image to GCR
        run: |
          docker tag martybobo/fungeye eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/martybobo/fungeye:${{ github.sha }}
          docker push eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/martybobo/fungeye:${{ github.sha }}

  deploy:
    needs: build
    name: Deploy to GCE
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Configure Docker to use GCR
        run: gcloud auth configure-docker eu.gcr.io
      - name: Download Docker image from GCR
        run: |
          docker pull eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/martybobo/fungeye:${{ github.sha }}
          docker tag eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/martybobo/fungeye:${{ github.sha }} martybobo/fungeye:${{ github.sha }}
      - name: Deploy Docker image to GCE
        run: |
          # Perform deployment to Google Compute Engine using the Docker image
          # Replace the following command with your actual deployment steps
          docker run -d --name fungeyecontainer martybobo/fungeye:${{ github.sha }}

