name: CI/CD Pipeline Master Deployment

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run Tests
        run: mvn -B test

  build:
    needs: tests
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml
      - run: mkdir staging && cp target/*.jar staging
      - name: Create app.yaml
        run: |
          echo "runtime: java17" > staging/app.yaml
          echo "env: flex" >> staging/app.yaml
          echo "instance_class: F2" >> staging/app.yaml
          echo "handlers:" >> staging/app.yaml
          echo "  - url: /.*" >> staging/app.yaml
          echo "    script: cloud-0.0.1-SNAPSHOT.jar" >> staging/app.yaml
          echo "automatic_scaling:" >> staging/app.yaml
          echo "max_idle_instances: automatic" >> staging/app.yaml
          echo "min_pending_latency: automatic" >> staging/app.yaml
          echo "max_pending_latency: automatic" >> staging/app.yaml


      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: FungEyeJar
          path: staging
      - name: Upload app.yaml Artifact
        uses: actions/upload-artifact@v3
        with:
          name: AppYAML
          path: staging/app.yaml

  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR Artifact
        uses: actions/download-artifact@v2
        with:
          name: FungEyeJar
          path: staging
      - name: Download app.yaml Artifact
        uses: actions/download-artifact@v2
        with:
          name: AppYAML
          path: staging
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true
      - name: Deploy to Google App Engine
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud app deploy staging/app.yaml
