name: CI/CD Pipeline Develop Branch

on:
  workflow_dispatch:
  push:
    branches: [develop]
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run Tests
        run: mvn -B test

jobs:
  build:
    needs: tests
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml
      - run: mkdir staging && cp target/*.jar staging
      - name: Create app.yaml
        run: |
          echo "runtime: java11" > staging/app.yaml
          echo "instance_class: F1" >> staging/app.yaml
          echo "entrypoint: 'java -jar FungEyeJar'" >> staging/app.yaml
          echo "handlers:" >> staging/app.yaml
          echo "  - url: /.*" >> staging/app.yaml
          echo "    script: this field is required, but ignored" >> staging/app.yaml
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: FungEyeJar
          path: staging
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true
      - name: Deploy to Google App Engine
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud app deploy staging/app.yaml
